$background = rgb(050000)
$foreground = rgb(F4F0D7)
$color0 = rgb(050000)
$color1 = rgb(635751)
$color2 = rgb(96562E)
$color3 = rgb(746285)
$color4 = rgb(8E837E)
$color5 = rgb(938984)
$color6 = rgb(A89F6A)
$color7 = rgb(E7E1BE)
$color8 = rgb(A29E85)
$color9 = rgb(84746B)
$color10 = rgb(C8723D)
$color11 = rgb(9B82B1)
$color12 = rgb(BDAFA8)
$color13 = rgb(C4B6B0)
$color14 = rgb(E0D48D)
$color15 = rgb(E7E1BE)
